// TEXTLIST.H - automatically generated by TextConvert.cpp

// This is a text dump list of the 'english.dat' file for Moho PC Release 2000 (needs to match the #define list below)
/*
0 = PRESS START BUTTON
1 = Select Character
2 = Enter Name for Save Game
3 = Select Prison
4 = Select Arena
5 = Cool Assassin
6 = Bringer Of Chaos
7 = Born To Drill
8 = Rolling Crimewave
9 = War Machine
10 = Surgical Precision
11 = Stats:
12 = Strength
13 = Speed
14 = Agility
15 = Stamina
16 = Eco Prison
17 = Zeppelin Prison
18 = Hospital
19 = Ship Prison
20 = Rehab
21 = Mining Prison
22 = Death Row
23 = Sports Prison
24 = Military Prison
25 = Alpha Star Complex
26 = Bonus Facility
27 = **ACCESS DENIED * *
28 = Security Level
29 = Inmates
30 = Escape Attempts
31 = Successful Escapes
32 = Arenas Completed
33 = Total Completed
34 = Needed To Access
35 = King Of The Hill
36 = Last Man Rolling
37 = Run The Gauntlet
38 = Pursuit
39 = Race
40 = Tag
41 = Powerball
42 = Golf
43 = Pinball
44 = Beam
45 = Objective:
46 = Claim the hill and keep it clear of inmates
47 = .
48 = Eliminate all inmates and guards
49 = .
50 = Get to the finish as quickly as possible
51 = .
52 = Get to the finish as quickly as possible
53 = .
54 = Outpace all opponents and win the race
55 = .
56 = Collect all tokens as quickly as possible
57 = .
58 = Score points by throwing balls at the target
59 = .
60 = Come in under par!
61 = .
62 = Use the Plasma beam to get the ball to the exit
63 = .
64 = Loading...
65 = Press[to shoot, and \ to look around.
66 = Remember you can brake!
67 = Arena Type :
68 = To Qualify :
69 = Gold Star :
70 = Lost Time :
71 = Your Best Time :
72 = Attempts :
73 = Continue
74 = Congratulations!You've unlocked:
75 = A new bonus arena
76 = A new character
77 = (C)2000 Lost Toys Ltd.All Rights Reserved
78 = Survive
79 = Win the Race
80 = Get to the Exit
81 = Beat
82 = Single Player
83 = Multiplayer
84 = Options
85 = Credits
86 = New Game
87 = Continue Game
88 = Load Game
89 = Abandon Current Game ?
90 = Controller Setup
91 = SFX Volume
92 = Music Volume
93 = Stereo Sound
94 = Vibration
95 = {
96 = |
97 = Player 1
98 = Player 2
99 = Setting:
100 = Jump
101 = Attack
102 = Block
103 = Throw
104 = Brake
105 = Chosen
106 = Select Tournament
107 = Looking for MEMORY CARD in MEMORY CARD slot 1
108 = .
109 = Do not remove MEMORY CARD
110 = No Ball Breakers save games found
111 = Select a game to load :
112 = Loading game...
113 = Game loaded successfully
114 = Game failed to load
115 = Insert a MEMORY CARD in MEMORY CARD slot 1
116 = .
117 = Insert another MEMORY CARD in MEMORY CARD slot 1
118 = .
119 = Save data is for a different version of MoHo
120 = Save Game
121 = Save Game ?
122 = Yes
123 = No
124 = Saving game...
125 = Save failed
126 = MEMORY CARD is unformatted
127 = Do you wish to format this MEMORY CARD ?
128 = .
129 = Formatting MEMORY CARD...
130 = Insufficient free blocks to save game
131 = Game saved successfully
132 = BACKSPACE
133 = ENTER
134 = @ to choose,[to select,] to go back
135 = [to continue
136 =] to go back
137 = @ to choose,[to select,] to go back,^ to save.
138 = Player 1 Wins!
139 = Player 2 Wins!
140 = Tournament Drawn.
141 = LEVEL WON
142 = LEVEL LOST
143 = LEVEL DRAWN
144 = Pos
145 = Lap
146 = Time
147 = Final Lap
148 = Required
149 = Tokens
150 = Player 1 - Insert Controller.
151 = Player 2 - Insert Controller.
152 = Restart Arena
153 = Exit Arena
154 = Powerball Cup
155 = Racing Class C
156 = Racing Class B
157 = Racing Class A
158 = Rolling Selection
159 = Mixed Class C
160 = Mixed Class B
161 = Mixed Class A
162 = Tag Cup
163 = Shot
164 = Par:
165 = Under Par
166 = 3 Under Par
167 = Your Best Score :
168 = Lost Score :
169 = EAGLE!
170 = Birdie!
171 = Par!
172 = Bogey!
173 = Double Bogey!
174 = @ to choose,[to select
175 = Lots...
176 = Format Failed
177 = Be King
178 = Error!That save game name is already in use
179 = Please try again
180 = Congratulations!
181 = Now go for the Lost Times!
182 = @ to choose,^ to select,] to go back
183 = ^ to continue
184 = ] to go back
185 = @ to choose,^ to select, ] to go back,[to save.
186 = @ to choose,^ to select
187 = Press ^ to shoot, and] to look around.
188 = Player 1 Pause
189 = Player 2 Pause
190 = A Controller has been removed,
191 = or a memory card is being recognised
192 = Select memory card
193 = % c   Port % c, Expansion Slot % d - Blocks free = % d
194 = Select memory card to use :
195 = A memory card with % d free blocks is required to save
196 = Please insert a memory card with % d free blocks
197 = No memory cards found
198 = If you press ^ to continue
199 = If you continue
200 = your progress will not be saved
201 = Select another memory card
202 = Continue
203 = { = existing save game found on memory card
204 = Saving...
205 = Do not turn the power off,
206 = or remove the memory card.
207 = Loading...
208 = Do not remove the memory card.
209 = Save Failed.
210 = Load Failed.
211 = Do you want to save or load from
212 = Port % c, Expansion Socket % d ?
213 = Loading will abandon the current game.
214 = Do you want to load ?
215 = A save game already exists on this memory card
216 = Do you want to overwrite ?
217 = Select Display Mode
218 = 50 Hz
219 = 60 Hz
220 = Test
221 = 60Hz mode will result in a smoother and faster
222 = screen update, but some TVs cannot accept this mode.
223 = If you are unsure if your TV can accept 60Hz,
224 = please select test option
225 = The display will now switch to 60Hz for 5 seconds.
226 = Please check that the image is displayed correctly.
227 = Testing 60Hz display...
228 = Was the image displayed correctly ?
229 = The memory card in use has been removed
230 = Please re - insert it now, into
231 = NOTE : if you insert a different memory card,
232 = any existing MoHo save data will be overwritten
233 = any existing Ball Breakers save data will be overwritten
234 = Port % c, Expansion Socket % d
235 = Do you want to quit ?
236 = File exists.Overwrite ?
237 = Press SPACE
238 = Exit Game
239 = MoHo
240 = Angel
241 = Apostle
242 = Benny
243 = Lockdown
244 = S0 - PH - 1E
245 = The Doctor
246 = The Pit
247 = Tabletop
248 = Ground Zero
249 = The Elbow
250 = Parklife
251 = Beamer
252 = Channel Run
253 = Helterskelter
254 = Rampish
255 = 10
256 = Trial by Fire
257 = Fire Ridge
258 = Marsh Rally
259 = 14
260 = Super Bowl
261 = Gateway
262 = 17
263 = Operating Table
264 = Pit Arena
265 = Crossfire
266 = High and Mighty
267 = Surfing 101
268 = The Waste Dump
269 = 24
270 = First Blood
271 = Laser Maze
272 = Speedway
273 = Mudskipper
274 = Hill of Jeopardy
275 = The Canyon
276 = Carver's Delight
277 = Showdown
278 = Razorblade Kisses
279 = Fortress
280 = T Junction
281 = Swamp Wave
282 = Under Pressure
283 = Racer's Leap
284 = Cannon Bowl
285 = Focal Point
286 = Eightway
287 = Double Whammy
288 = Swamp Hopper
289 = The 5 Chambers
290 = Island of Hurt
291 = Surviving the Y
292 = Crossbowl
293 = Switch Hitter
294 = Warehouse
295 = Laser Run
296 = Bombshell
297 = Apex Twin
298 = The Snake
299 = Gun Alley
300 = Pits of Fury
301 = Highpass Loop
302 = Shellshock
303 = Wave Hill
304 = Switchback
305 = Plateau of Peril
306 = Prize Fighter
307 = Pipe Ruins
308 = X - Up
309 = Dos Dedos
310 = Straight Up
311 = Downtown
312 = Fireball
313 = Showtime
314 = Circuitous
315 = Gridiron
316 = The Borehole
317 = Under Fire
318 = Slider
319 = Gillam's Island
320 = Benny's Pit
321 = Angel's Arena
322 = Sophie's Gauntlet
323 = Apostle's Temple
324 = Lockdown's Lair
325 = Final Conflict
326 = Speedway
327 = Eightway
328 = Krypton's Revenge
329 = Holeshot
330 = T Junction
331 = Racer's Leap
332 = Laser Maze
333 = Gun Alley
334 = Straight Up
335 = X - Up
336 = Circuitous
337 = Two Into One
338 = Gridiron
339 = Highpass Loop
340 = The Pit
341 = Halfball
342 = Storage
343 = Crossbowl
344 = The Waste Dump
345 = Front 3
346 = Turn 3
347 = Back 3
348 = Beamer
349 = Helterskelter
350 = 1 UP
351 = 2 UP
352 = OB!
353 = Designed and Developed by Lost Toys :
354 = Project Lead / Lead Programmer
355 = Lead Artist
356 = Lead Designer
357 = Programming
358 = Art
359 = Additional Art
360 = Music
361 = Sound Effects
362 = Special Thanks to :
363 = Thanks to
364 = Thanks also to all those on GGDev
365 = Broadsword Interactive :
366 = PC Programming
367 = Additional PC Programming
368 = Management
369 = Take 2 Interactive UK :
370 = Producer
371 = Assistant Producer
372 = UK PR Manager
373 = UK Marketing Manager
374 = International Marketing Manager
375 = Group Production Manager
376 = Group Production Co - ordinator
377 = Technical Services Manager
378 = Tarantula Studios(QA HQ) :
379 = QA Manager
380 = Lead Testers
381 = Testers
382 = MoHo Demo
383 = Quit Demo
384 = Your Code
385 = Demo Timeout!
386 = @ to choose,[to select,] to exit demo
387 = @ to choose,[to select
388 = OK
*/

#define	TEXT_PRESS_START                                       0
#define	TEXT_CHARACTER_SELECT                                  1
#define	TEXT_ENTER_NAME                                        2
#define	TEXT_PRISON_SELECT                                     3
#define	TEXT_ARENA_SELECT                                      4
#define	TEXT_ANGEL_COMMENT                                     5
#define	TEXT_APOSTLE_COMMENT                                   6
#define	TEXT_BENNY_COMMENT                                     7
#define	TEXT_LOCKDOWN_COMMENT                                  8
#define	TEXT_SOPHIE_COMMENT                                    9
#define	TEXT_DOCTOR_COMMENT                                    10
#define	TEXT_STATS                                             11
#define	TEXT_STRENGTH                                          12
#define	TEXT_SPEED                                             13
#define	TEXT_AGILITY                                           14
#define	TEXT_STAMINA                                           15
#define	TEXT_PRN_ECO                                           16
#define	TEXT_PRN_ZEPPELIN                                      17
#define	TEXT_PRN_HOSPITAL                                      18
#define	TEXT_PRN_SHIP                                          19
#define	TEXT_PRN_REHAB                                         20
#define	TEXT_PRN_MINING                                        21
#define	TEXT_PRN_DEATHROW                                      22
#define	TEXT_PRN_SPORTS                                        23
#define	TEXT_PRN_MILITARY                                      24
#define	TEXT_PRN_ALPHASTAR                                     25
#define	TEXT_PRN_BONUS                                         26
#define	TEXT_ACCESS_DENIED                                     27
#define	TEXT_SECURITY_LEVEL                                    28
#define	TEXT_INMATES                                           29
#define	TEXT_ESCAPE_ATTEMPTS                                   30
#define	TEXT_SUCCESSFUL_ESCAPES                                31
#define	TEXT_ARENAS_COMPLETED                                  32
#define	TEXT_TOTAL_ARENAS_COMPLETED                            33
#define	TEXT_ARENAS_NEEDED_TO_ACCESS                           34
#define	TEXT_LT_KING_OF_THE_HILL                               35
#define	TEXT_LT_LAST_MAN_ROLLING                               36
#define	TEXT_LT_RUN_THE_GAUNTLET                               37
#define	TEXT_LT_PURSUIT                                        38
#define	TEXT_LT_RACE                                           39
#define	TEXT_LT_TRICK                                          40
#define	TEXT_LT_POWERBALL                                      41
#define	TEXT_LT_GOLF                                           42
#define	TEXT_LT_PINBALL                                        43
#define	TEXT_LT_SBALL                                          44
#define	TEXT_OBJECTIVE                                         45
#define	TEXT_NOTES_KING_A                                      46
#define	TEXT_NOTES_KING_B                                      47
#define	TEXT_NOTES_LAST_MAN_A                                  48
#define	TEXT_NOTES_LAST_MAN_B                                  49
#define	TEXT_NOTES_GAUNTLET_A                                  50
#define	TEXT_NOTES_GAUNTLET_B                                  51
#define	TEXT_NOTES_PURSUIT_A                                   52
#define	TEXT_NOTES_PURSUIT_B                                   53
#define	TEXT_NOTES_RACE_A                                      54
#define	TEXT_NOTES_RACE_B                                      55
#define	TEXT_NOTES_TRICK_A                                     56
#define	TEXT_NOTES_TRICK_B                                     57
#define	TEXT_NOTES_BALL_A                                      58
#define	TEXT_NOTES_BALL_B                                      59
#define	TEXT_NOTES_GOLF_A                                      60
#define	TEXT_NOTES_GOLF_B                                      61
#define	TEXT_NOTES_SBALL_A                                     62
#define	TEXT_NOTES_SBALL_B                                     63
#define	TEXT_LOADING                                           64
#define	TEXT_HELP_GOLF                                         65
#define	TEXT_HELP_BEAM                                         66
#define	TEXT_LEVEL_TYPE                                        67
#define	TEXT_QUALIFY                                           68
#define	TEXT_GOLD                                              69
#define	TEXT_LOST_TOYS_TIME                                    70
#define	TEXT_BEST_TIME                                         71
#define	TEXT_NUM_ATTEMPTS                                      72
#define	TEXT_CONTINUE                                          73
#define	TEXT_CONGRATS1                                         74
#define	TEXT_BONUS_LEVEL                                       75
#define	TEXT_BONUS_CHARACTER                                   76
#define	TEXT_COPYRIGHT                                         77
#define	TEXT_LIFIN_SURVIVE                                     78
#define	TEXT_LIFIN_WIN                                         79
#define	TEXT_LIFIN_FINISH                                      80
#define	TEXT_LIFIN_BEAT                                        81
#define	TEXT_SINGLE_PLAYER                                     82
#define	TEXT_MULTIPLAYER                                       83
#define	TEXT_OPTIONS                                           84
#define	TEXT_CREDITS                                           85
#define	TEXT_NEW_GAME                                          86
#define	TEXT_CONTINUE_GAME                                     87
#define	TEXT_LOAD_GAME                                         88
#define	TEXT_ABANDON_GAME                                      89
#define	TEXT_CONTROLLER_SETUP                                  90
#define	TEXT_SOUND_VOLUME                                      91
#define	TEXT_MUSIC_VOLUME                                      92
#define	TEXT_STEREO_SOUND                                      93
#define	TEXT_VIBRATION                                         94
#define	TEXT_ON                                                95
#define	TEXT_OFF                                               96
#define	TEXT_PLAYER_1                                          97
#define	TEXT_PLAYER_2                                          98
#define	TEXT_SETTING                                           99
#define	TEXT_JUMP                                              100
#define	TEXT_ATTACK                                            101
#define	TEXT_BLOCK                                             102
#define	TEXT_THROW                                             103
#define	TEXT_BRAKE                                             104
#define	TEXT_CHOSEN                                            105
#define	TEXT_TOURNAMENT_SELECT                                 106
#define	TEXT_LOAD_LOOKING_A                                    107
#define	TEXT_LOAD_LOOKING_B                                    108
#define	TEXT_LOAD_REMOVE                                       109
#define	TEXT_LOAD_NONE                                         110
#define	TEXT_LOAD_SELECT                                       111
#define	TEXT_LOAD_LOADING                                      112
#define	TEXT_LOAD_LOADED                                       113
#define	TEXT_LOAD_FAILED                                       114
#define	TEXT_LOAD_INSERT_A                                     115
#define	TEXT_LOAD_INSERT_B                                     116
#define	TEXT_LOAD_INSERT2_A                                    117
#define	TEXT_LOAD_INSERT2_B                                    118
#define	TEXT_LOAD_WRONG_VERSION                                119
#define	TEXT_SAVE_GAME                                         120
#define	TEXT_QSAVE_GAME                                        121
#define	TEXT_YES                                               122
#define	TEXT_NO                                                123
#define	TEXT_SAVE_SAVING                                       124
#define	TEXT_SAVE_FAILED                                       125
#define	TEXT_SAVE_UNFORMATTED                                  126
#define	TEXT_SAVE_UNFORMATTED2_A                               127
#define	TEXT_SAVE_UNFORMATTED2_B                               128
#define	TEXT_SAVE_FORMATTING                                   129
#define	TEXT_SAVE_NO_SPACE                                     130
#define	TEXT_SAVE_SAVED                                        131
#define	TEXT_BACKSPACE                                         132
#define	TEXT_ENTER                                             133
#define	TEXT_HELP1                                             134
#define	TEXT_HELP2                                             135
#define	TEXT_HELP3                                             136
#define	TEXT_HELP4                                             137
#define	TEXT_P1WINS                                            138
#define	TEXT_P2WINS                                            139
#define	TEXT_TOURNAMENT_DRAWN                                  140
#define	TEXT_LEVEL_WON                                         141
#define	TEXT_LEVEL_LOST                                        142
#define	TEXT_LEVEL_DRAWN                                       143
#define	TEXT_POS                                               144
#define	TEXT_LAP_NUMBER                                        145
#define	TEXT_LAP_TIME                                          146
#define	TEXT_FINAL_LAP                                         147
#define	TEXT_REQUIRED                                          148
#define	TEXT_TOKENS                                            149
#define	TEXT_INSERT1                                           150
#define	TEXT_INSERT2                                           151
#define	TEXT_RESTART_ARENA                                     152
#define	TEXT_EXIT_ARENA                                        153
#define	TEXT_TNAME_00                                          154
#define	TEXT_TNAME_01                                          155
#define	TEXT_TNAME_02                                          156
#define	TEXT_TNAME_03                                          157
#define	TEXT_TNAME_04                                          158
#define	TEXT_TNAME_05                                          159
#define	TEXT_TNAME_06                                          160
#define	TEXT_TNAME_07                                          161
#define	TEXT_TNAME_08                                          162
#define	TEXT_SHOT                                              163
#define	TEXT_LIFIN_PAR                                         164
#define	TEXT_LIFIN_UNDERPAR                                    165
#define	TEXT_LIFIN_3UNDERPAR                                   166
#define	TEXT_BEST_SCORE                                        167
#define	TEXT_LOST_SCORE                                        168
#define	TEXT_EAGLE                                             169
#define	TEXT_BIRDIE                                            170
#define	TEXT_PAR                                               171
#define	TEXT_BOGIE                                             172
#define	TEXT_DOUBLE_BOGIE                                      173
#define	TEXT_HELP5                                             174
#define	TEXT_LOTS                                              175
#define	TEXT_FORMAT_FAILED                                     176
#define	TEXT_LIFIN_WIN2                                        177
#define	TEXT_NAME_ERROR1                                       178
#define	TEXT_NAME_ERROR2                                       179
#define	TEXT_ALL_GOLD1                                         180
#define	TEXT_ALL_GOLD2                                         181
#define	TEXT_HELPDC1                                           182
#define	TEXT_HELPDC2                                           183
#define	TEXT_HELPDC3                                           184
#define	TEXT_HELPDC4                                           185
#define	TEXT_HELPDC5                                           186
#define	TEXT_HELPDC_GOLF                                       187
#define	TEXT_DC_PLAYER1_PAUSE                                  188
#define	TEXT_DC_PLAYER2_PAUSE                                  189
#define	TEXT_DC_CONTROLLER_REMOVED                             190
#define	TEXT_DC_MEMCARD_RECOGNISED                             191
#define	TEXT_DC_SELECT_MEMORY_CARD                             192
#define	TEXT_DC_PORT_SOCKET_BLOCKS                             193
#define	TEXT_DC_CHOOSE_MEMORY_CARD                             194
#define	TEXT_DC_BLOCKS_REQUIRED                                195
#define	TEXT_DC_INSERT_CARD                                    196
#define	TEXT_DC_NO_CARDS                                       197
#define	TEXT_DC_NO_SAVE1                                       198
#define	TEXT_DC_NO_SAVE1A                                      199
#define	TEXT_DC_NO_SAVE2                                       200
#define	TEXT_DC_SELECT_AGAIN                                   201
#define	TEXT_DC_CONTINUE                                       202
#define	TEXT_DC_SAVE_PRESENT                                   203
#define	TEXT_DC_SAVING1                                        204
#define	TEXT_DC_SAVING2                                        205
#define	TEXT_DC_SAVING3                                        206
#define	TEXT_DC_LOADING1                                       207
#define	TEXT_DC_LOADING2                                       208
#define	TEXT_DC_SAVE_FAILED                                    209
#define	TEXT_DC_LOAD_FAILED                                    210
#define	TEXT_DC_SAVE_LOAD                                      211
#define	TEXT_DC_PORT_SOCKET                                    212
#define	TEXT_DC_LOAD_YN1                                       213
#define	TEXT_DC_LOAD_YN2                                       214
#define	TEXT_DC_SAVE_YN1                                       215
#define	TEXT_DC_SAVE_YN2                                       216
#define	TEXT_DC_SEL_DISPLAY                                    217
#define	TEXT_DC_50HZ                                           218
#define	TEXT_DC_60HZ                                           219
#define	TEXT_DC_TEST                                           220
#define	TEXT_DC_60MESS1                                        221
#define	TEXT_DC_60MESS2                                        222
#define	TEXT_DC_60MESS3                                        223
#define	TEXT_DC_60MESS4                                        224
#define	TEXT_DC_60TEST1                                        225
#define	TEXT_DC_60TEST2                                        226
#define	TEXT_DC_60TESTING                                      227
#define	TEXT_DC_60RESPONSE                                     228
#define	TEXT_DC_CARD_REMOVED1                                  229
#define	TEXT_DC_CARD_REMOVED2                                  230
#define	TEXT_DC_CARD_REMOVED3                                  231
#define	TEXT_DC_CARD_REMOVED4M                                 232
#define	TEXT_DC_CARD_REMOVED4B                                 233
#define	TEXT_DC_PORT_SOCKET2                                   234
#define	TEXT_PC_CONFIRM_QUIT_GAME                              235
#define	TEXT_PC_OVERWRITE                                      236
#define	TEXT_PC_PRESS_SPACE                                    237
#define TEXT_EXIT                                              238
#define	TEXT_TITLE                                             239
#define	TEXT_ANGEL                                             240
#define	TEXT_APOSTLE                                           241
#define	TEXT_BENNY                                             242
#define	TEXT_LOCKDOWN                                          243
#define	TEXT_SOHPIE                                            244
#define	TEXT_DOCTOR                                            245
#define	TEXT_LNAME_001                                         246
#define	TEXT_LNAME_002                                         247
#define	TEXT_LNAME_003                                         248
#define	TEXT_LNAME_004                                         249
#define	TEXT_LNAME_005                                         250
#define	TEXT_LNAME_006                                         251
#define	TEXT_LNAME_007                                         252
#define	TEXT_LNAME_008                                         253
#define	TEXT_LNAME_009                                         254
#define	TEXT_LNAME_010                                         255
#define	TEXT_LNAME_011                                         256
#define	TEXT_LNAME_012                                         257
#define	TEXT_LNAME_013                                         258
#define	TEXT_LNAME_014                                         259
#define	TEXT_LNAME_015                                         260
#define	TEXT_LNAME_016                                         261
#define	TEXT_LNAME_017                                         262
#define	TEXT_LNAME_018                                         263
#define	TEXT_LNAME_019                                         264
#define	TEXT_LNAME_020                                         265
#define	TEXT_LNAME_021                                         266
#define	TEXT_LNAME_022                                         267
#define	TEXT_LNAME_023                                         268
#define	TEXT_LNAME_024                                         269
#define	TEXT_LNAME_025                                         270
#define	TEXT_LNAME_026                                         271
#define	TEXT_LNAME_027                                         272
#define	TEXT_LNAME_028                                         273
#define	TEXT_LNAME_029                                         274
#define	TEXT_LNAME_030                                         275
#define	TEXT_LNAME_031                                         276
#define	TEXT_LNAME_032                                         277
#define	TEXT_LNAME_033                                         278
#define	TEXT_LNAME_034                                         279
#define	TEXT_LNAME_035                                         280
#define	TEXT_LNAME_036                                         281
#define	TEXT_LNAME_037                                         282
#define	TEXT_LNAME_038                                         283
#define	TEXT_LNAME_039                                         284
#define	TEXT_LNAME_040                                         285
#define	TEXT_LNAME_041                                         286
#define	TEXT_LNAME_042                                         287
#define	TEXT_LNAME_043                                         288
#define	TEXT_LNAME_044                                         289
#define	TEXT_LNAME_045                                         290
#define	TEXT_LNAME_046                                         291
#define	TEXT_LNAME_047                                         292
#define	TEXT_LNAME_048                                         293
#define	TEXT_LNAME_049                                         294
#define	TEXT_LNAME_050                                         295
#define	TEXT_LNAME_051                                         296
#define	TEXT_LNAME_052                                         297
#define	TEXT_LNAME_053                                         298
#define	TEXT_LNAME_054                                         299
#define	TEXT_LNAME_055                                         300
#define	TEXT_LNAME_056                                         301
#define	TEXT_LNAME_057                                         302
#define	TEXT_LNAME_058                                         303
#define	TEXT_LNAME_059                                         304
#define	TEXT_LNAME_060                                         305
#define	TEXT_LNAME_061                                         306
#define	TEXT_LNAME_062                                         307
#define	TEXT_LNAME_063                                         308
#define	TEXT_LNAME_064                                         309
#define	TEXT_LNAME_065                                         310
#define	TEXT_LNAME_066                                         311
#define	TEXT_LNAME_067                                         312
#define	TEXT_LNAME_068                                         313
#define	TEXT_LNAME_069                                         314
#define	TEXT_LNAME_070                                         315
#define	TEXT_LNAME_071                                         316
#define	TEXT_LNAME_072                                         317
#define	TEXT_LNAME_073                                         318
#define	TEXT_LNAME_074                                         319
#define	TEXT_LNAME_075                                         320
#define	TEXT_LNAME_076                                         321
#define	TEXT_LNAME_077                                         322
#define	TEXT_LNAME_078                                         323
#define	TEXT_LNAME_079                                         324
#define	TEXT_LNAME_080                                         325
#define	TEXT_LNAME_101                                         326
#define	TEXT_LNAME_102                                         327
#define	TEXT_LNAME_103                                         328
#define	TEXT_LNAME_104                                         329
#define	TEXT_LNAME_105                                         330
#define	TEXT_LNAME_106                                         331
#define	TEXT_LNAME_107                                         332
#define	TEXT_LNAME_108                                         333
#define	TEXT_LNAME_109                                         334
#define	TEXT_LNAME_110                                         335
#define	TEXT_LNAME_111                                         336
#define	TEXT_LNAME_112                                         337
#define	TEXT_LNAME_113                                         338
#define	TEXT_LNAME_114                                         339
#define	TEXT_LNAME_115                                         340
#define	TEXT_LNAME_116                                         341
#define	TEXT_LNAME_117                                         342
#define	TEXT_LNAME_118                                         343
#define	TEXT_LNAME_119                                         344
#define	TEXT_LNAME_201                                         345
#define	TEXT_LNAME_204                                         346
#define	TEXT_LNAME_207                                         347
#define	TEXT_LNAME_210                                         348
#define	TEXT_LNAME_211                                         349
#define	TEXT_1UP                                               350
#define	TEXT_2UP                                               351
#define	TEXT_OB                                                352
#define	TEXT_CRED1                                             353
#define	TEXT_CRED2                                             354
#define	TEXT_CRED3                                             355
#define	TEXT_CRED4                                             356
#define	TEXT_CRED5                                             357
#define	TEXT_CRED6                                             358
#define	TEXT_CRED7                                             359
#define	TEXT_CRED8                                             360
#define	TEXT_CRED9                                             361
#define	TEXT_CRED10                                            362
#define	TEXT_CRED11                                            363
#define	TEXT_CRED12                                            364
#define	TEXT_CRED13                                            365
#define	TEXT_CRED14                                            366
#define	TEXT_CRED15                                            367
#define	TEXT_CRED16                                            368
#define	TEXT_CRED17                                            369
#define	TEXT_CRED18                                            370
#define	TEXT_CRED19                                            371
#define	TEXT_CRED20                                            372
#define	TEXT_CRED21                                            373
#define	TEXT_CRED22                                            374
#define	TEXT_CRED23                                            375
#define	TEXT_CRED24                                            376
#define	TEXT_CRED25                                            377
#define	TEXT_CRED26                                            378
#define	TEXT_CRED27                                            379
#define	TEXT_CRED28                                            380
#define	TEXT_CRED29                                            381
#define	TEXT_MOHO_DEMO                                         382
#define	TEXT_QUIT_DEMO                                         383
#define	TEXT_YOUR_CODE                                         384
#define	TEXT_DEMO_TIMEOUT                                      385
#define	TEXT_DEMO_HELP1                                        386
#define	TEXT_DEMO_HELP2                                        387
#define	TEXT_OK                                                388
